default_context:
    repo_name: "dtu-mlops-project"
    project_name: "mlops"
    project_structure: "advance"
    deps_manager: "uv"
    add_coding_agent_support: true
    author_name: "Group 48"
    description: "description"
    python_version: "3.12"
    open_source_license: "MIT"